spring.application.name=game_of_advoisors
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
game-of-advisors.security.admin-github-ids=${ADMIN_GITHUB_IDS:}